apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: academa
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
